version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 15672:15672
    volumes:
      - ./conf/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./conf/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - services
  computer:
    build:
      context: ./conf/consumers
    networks:
      - services
    working_dir: /consumers
    volumes:
      - ./conf/consumers:/consumers
    entrypoint: /usr/bin/env
    command: python main.py
  redis:
    image: redis:alpine
    networks:
      - services
    ports:
      - 6379:6379
      

networks:
  services:
